### ISSUE TITLE
Does not open in non-condensed mode

### ISSUE THREAD

**Issue by malzaeem** [v0ltoz/react-datetimepicker#28]
When using this component it shows in condensed mode rather that in full width mode. Can I change that behavior, and can I change it to open to the left. 

![image](https://user-images.githubusercontent.com/51410905/61397039-080b5800-a897-11e9-908f-c597a796dad3.png)

**Comment by Valeriyspk** [comment]
Came here to open identical issue.
Automatic select of side to open (left/right) depending on the component location on the screen seems best option, but, at least optional prop to switch side would be very appreciated.

**Comment by v0ltoz** [comment]
@malzaeem I have introduced noMobileMode as a prop in 1.0.6 which should allow you to permanently set the picker to not condense at the mobile breakpoint.

@Valeriyspk I have added leftMode which when set should allow you to open on the left-hand side instead of the right. 

Let me know how you get on with these features as I have done then as BETA at the minute as I wanted your feedback.
